[package]
name = "coding_interview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mylib"
path = "src/lib/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin/main.rs"

[dependencies]
rand = "0.8"
