pub mod first_occurance;
pub mod length_of_last_word;
pub mod longst_common_prefix;
pub mod majority_element;
pub mod merge_sorted_array;
pub mod remove_duplicate_from_sorted_arry;
pub mod remove_element_27;
pub mod roman_to_integer;
pub mod valid_palindrome_125;
